Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  masterHost: "127.0.0.1"
  masterPort: "42000"
  copyright: Copyright (c) 2014 Christopher Blöcker. All rights reserved
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
